# Site settings
title: Cup Full of Code
email: keelerm@tortugas-llc.com
description: "The personal blog of Matthew M. Keeler"
baseurl: ""
url: "http://cupfullofcode.com"
twitter_username: keelerm84
github_username:  keelerm84

# Build settings
timezone: America/New_York
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 5

gems: [jekyll-sass]
